name: test CI

on:
  workflow_dispatch:
  schedule:
    - cron: "13 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # - name: 检查当前 CI 服务器 IP 及访问情况
      #   run: |
      #     # 获取当前公网 IP
      #     echo "当前 CI 服务器 IP："
      #     curl -s http://icanhazip.com  # 或 https://api.ipify.org
          
      #     # 测试目标服务器是否可访问（不发送业务请求，仅检查基础连通性）
      #     echo "测试访问目标服务器..."
      #     curl -v https://app.mixcapp.com  # 仅访问域名根路径，避免接口权限问题
      #     # 或测试目标接口的 OPTIONS 方法（预检请求）
      #     curl -X OPTIONS -v https://app.mixcapp.com/mixc/gateway
      - name: 测试代理连通性
        run: |
          curl -x https://jzcs-test.expowh.com -v https://app.mixcapp.com/mixc/gateway
        
